name: Build Tumleweed-dnf
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get date snapshot
      run: export SNAPSHOT="$(date +'%Y%m%d')"
    
    - name: Setup Multi-Arch builds
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Buildah
      uses: redhat-actions/buildah-build@v2
      with:
        image: tumbleweed-toolbox
        tags: v1 ${{ github.sha }} SNAPSHOT
        dockerfiles: |
          ./images/opensuse/tw/dnf/Dockerfile
        build-args: |
          some_arg=some_value